### PR TITLE
filter out assets hidden by Webpack

### PR DESCRIPTION
**Pull request by mindtraveller**
remove empty entries from the stats when Webpack's stats.excludeAssets is used e.g.
image

in the cause above Webpack generates an asset with type 'hidden assets' for all filtered out assets, this PR ignores such assets in stats comparison table

### CODE REVIEW

**Comment by mattcosta7** [comment]
@mindtraveller thanks for this suggested fix!  Could you take a few steps here.

1. Would you mind writing up a PR body for this?  I understand the suggested change, but this will be helpful for future context.
2. In order to build an action, the bundled code is checked in. Could you run `npm run all` and commit the changed files then push a new commit

**Comment by mindtraveller** [comment]
@mattcosta7 done

**Comment by mindtraveller** [comment]
@mattcosta7 when it's possible to expect this PR being merged and released?

**Review by mattcosta7 — APPROVED** [review]

**Comment by mattcosta7** [comment]
> @mattcosta7 when it's possible to expect this PR being merged and released?

https://github.com/github/webpack-bundlesize-compare-action/releases/tag/v1.8.0

**Pull request merged**
