### PR TITLE
Add module size analysis

### PR DESCRIPTION
**Pull request by camchenry**
This PR adds a more detailed bundle size analysis than just the aggregate asset size, which includes only files that were changed (i.e., added, removed, made larger, or made smaller).

The changeset table is sorted from largest diff percentage to smallest diff percentage, so that large bundle size increases (in relative terms) are highlighted first. The newly added stats files were derived from a much larger `stats.json` file which reflects real-world usage. The new changeset table will only be generated if `chunks` information is available. Otherwise, it will not be shown.

The following is an example of what the Bundle Stats comment looks like now:

---

# Bundle Stats

Hey there, this message comes from a [GitHub action](https://github.com/github/webpack-bundlesize-compare-action) that helps you and reviewers to understand how these changes affect the size of this project's bundle.

As this PR is updated, I'll keep you updated on how the bundle size is impacted.

**Total**

Files count | Type | Total bundle size | % Changed
----------- | ---- | ----------------- | ---------
2 | bundled | 1.98 MB | 0%

**Changeset**

File | Size | % Changed
---- | ---- | ---------
./src/client/this-file-was-added.ts | 0 Bytes -> 1.46 KB (+1.46 KB) | -
./src/client/this-file-grew-larger.tsx | 562 Bytes -> 762 Bytes (+200 Bytes) | +35.59%
./src/client/helpers/this-file-grew-smaller.ts | 2.46 KB -> 2.26 KB (-200 Bytes) | -7.94%
./src/client/this-file-will-be-deleted.ts | 1.46 KB -> 0 Bytes (-1.46 KB) | -100%

<details>
<summary>View detailed bundle breakdown</summary>

<div>

**Added**

No assets were added

**Removed**

No assets were removed

**Bigger**

No assets were bigger

**Smaller**

No assets were smaller

**Unchanged**

Asset | Type | File Size | % Changed
----- | ---- | --------- | ---------
app.bundle.js | bundled | 1.98 MB | 0%
manifest.json | bundled | 91 Bytes | 0%

</div>
</details>

### CODE REVIEW

**Review by iansan5653 — APPROVED** [review]
Looks great to me.

Doesn't have to be this PR, but what do you think of adding indicator icons to the table to make it more scannable? Something like 🔴 for increase, 🟢 for decrease? Or alternatively 📈 / 📉 .

**Comment by mattcosta7** [comment]
One question re the changset here - do we want to account for things like "which bundles are these in"

A single webpack stats.json might have multiple output files (which are the things this action compares currently).  Single files in a bundle might exist in multiple bundles.  Should we link back to the files these items are bundled in somehow to display this?

**Comment by camchenry** [comment]
> 

I love it! I had the same thought, but I think we can do that in a follow-up PR and experiment with some different indicators.

**Comment by mattcosta7** [comment]
Should we add an additional 'workflow' that outputs something with a changeset that displays on every PR?

**Comment by camchenry** [comment]
> One question re the changset here - do we want to account for things like "which bundles are these in"
> 
> A single webpack stats.json might have multiple output files (which are the things this action compares currently). Single files in a bundle might exist in multiple bundles. Should we link back to the files these items are bundled in somehow to display this?

Great point! Currently the modules are flattened out to just a single list, but we are accessing them via `chunk.modules.modules`, so it wouldn't be hard to include which chunk each module is part of, or generate a separate table of files for each chunk, depending on how we want to display it. For example:

**Chunk 1**

(table of files)

**Chunk 2**

(table of files)

Or alternatively, show the chunk each file belongs to:

**Changeset**

| File | Size | % changed |
| ---- | ---- | ---- |
| chunk 1 / file 1 | ... | ... |
| chunk 2 / file 1 | ... | ... |
| chunk 1 / file 2 | ... | ... |
| chunk 1 / file 3 | ... | ... |
| chunk 2 / file 2 | ... | ... |


> Should we add an additional 'workflow' that outputs something with a changeset that displays on every PR?
> 
> https://github.com/github/webpack-bundlesize-compare-action/blob/main/.github/workflows/test.yml#L23-L49

Good call, I'll update the workflows.

**Comment by camchenry** [comment]
@mattcosta7 I added another workflow with changeset information. Regarding handling multiple chunks, I think we can handle this whenever we start splitting up more files by route and such, but for now it's not a common usecase, so it could just be a follow-up later.

**Pull request merged**
